import { createRequire } from "node:module";
import path from "node:path";
import { pathToFileURL } from "node:url";
const require = createRequire(import.meta.url);
const user = process.env.USERPROFILE || process.env.HOME;
const modulePath = process.env.PLAYWRIGHT_MODULE || path.join(user, ".cache", "codex-runtimes", "codex-primary-runtime", "dependencies", "node", "node_modules", "playwright");
const { chromium } = require(modulePath);
const root = path.resolve(import.meta.dirname, "..", "..");
const url = pathToFileURL(path.join(root, "dist", "index.html")).href;
const executablePath = process.env.BROWSER_EXE || "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe";
const browser = await chromium.launch({headless:true, executablePath});
const page = await browser.newPage({viewport:{width:375,height:760}});
const consoleErrors=[]; page.on("console",(msg)=>{if(msg.type()==="error") consoleErrors.push(msg.text());});
await page.goto(url); await page.waitForFunction(()=>globalThis.__M4_TEST__?.ready);
if((await page.evaluate(()=>globalThis.__M4_TEST__.normalizationFailures)).length) throw new Error("browser normalization failed");
if(!(await page.evaluate(()=>JSON.parse(document.getElementById("drill-data").textContent).special_character_probe)).startsWith("</script>")) throw new Error("embedded special-character data changed");
await page.getByLabel("本番教材").check(); await page.getByRole("button",{name:"回答する"}).press("Enter"); await page.getByText("不正解です。",{exact:false}).waitFor();
await page.getByRole("button",{name:"再挑戦"}).press("Enter"); await page.getByLabel("検査用データ").check(); await page.getByRole("button",{name:"回答する"}).press("Enter"); await page.getByText("正解です。",{exact:false}).waitFor();
await page.getByRole("button",{name:"次の問題"}).press("Enter"); if(!(await page.getByRole("heading",{name:"問題"}).evaluate((node)=>node===document.activeElement))) throw new Error("question heading did not receive focus");
await page.getByLabel("回答").fill("PŪELLA"); await page.getByLabel("回答").press("Enter"); await page.getByText("正解です。",{exact:false}).waitFor();
await page.getByRole("button",{name:"次の問題"}).press("Enter"); await page.getByLabel("格").selectOption("主格"); await page.getByLabel("数").selectOption("単数"); await page.getByRole("button",{name:"回答する"}).press("Enter");
const saved = await page.evaluate(()=>localStorage.length > 0); if(!saved) throw new Error("progress not saved");
await page.reload(); await page.waitForFunction(()=>globalThis.__M4_TEST__?.ready); if((await page.evaluate(()=>globalThis.__M4_TEST__.state().correct)) < 1) throw new Error("progress not restored");
await page.evaluate(()=>localStorage.setItem("latin-learning-system:m4-demo:v1","{broken")); await page.reload(); await page.waitForFunction(()=>globalThis.__M4_TEST__?.ready); if((await page.evaluate(()=>globalThis.__M4_TEST__.state().index))!==0) throw new Error("corrupt progress not reset");
await page.evaluate(()=>localStorage.setItem("latin-learning-system:m4-demo:v1",JSON.stringify({schema_version:"old",content_version:"old",unit_id:"demo-m4",index:2,correct:9,answered:true}))); await page.reload(); await page.waitForFunction(()=>globalThis.__M4_TEST__?.ready); if((await page.evaluate(()=>globalThis.__M4_TEST__.state().correct))!==0) throw new Error("version-mismatched progress not reset");
await page.getByRole("button",{name:"履歴をリセット"}).click(); await page.getByRole("button",{name:"削除する"}).click();
for (const width of [320,768,1280]) { await page.setViewportSize({width,height:800}); const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth); if(overflow) throw new Error(`horizontal overflow at ${width}`); }
await page.setViewportSize({width:320,height:800}); await page.evaluate(()=>document.body.style.zoom="200%"); if(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth*2)) throw new Error("unusable overflow at 200% zoom"); await page.evaluate(()=>document.body.style.zoom="");
await page.emulateMedia({media:"print"}); if(await page.getByRole("button",{name:"回答する"}).isVisible()) throw new Error("print controls visible");
await page.emulateMedia({media:"screen"});
await page.goto(url+"?storage=fail"); await page.waitForFunction(()=>globalThis.__M4_TEST__?.ready); if((await page.evaluate(()=>globalThis.__M4_TEST__.storageMode()))!=="memory") throw new Error("memory fallback not active");
await page.getByLabel("検査用データ").check(); await page.getByRole("button",{name:"回答する"}).press("Enter"); if((await page.evaluate(()=>globalThis.__M4_TEST__.state().correct))!==1) throw new Error("memory fallback session did not continue");
if(consoleErrors.length) throw new Error("console errors: "+consoleErrors.join(" | "));
await browser.close(); console.log("Browser drill regression: passed.");
