const assert=require('node:assert/strict');
const M=require('./core.js');
const plain=M.createGame(M.createTorusDemo({loopLearning:true}));
assert.equal(M.knowledgeSummary(plain).rank,0);assert.equal(M.knowledgeSummary(plain).index,null);
const diagonal=M.createGame(M.createTorusDemo({diagonalRoom:true,selfVision:true,loopLearning:true}));
assert.equal(M.knowledgeSummary(diagonal).rank,1);assert.equal(M.knowledgeSummary(diagonal).complete,false);
const crossed=M.createGame(M.createTorusDemo({diagonalRoom:'crossed',selfVision:true,loopLearning:true}));
assert.equal(crossed.cognition.known_loops.size,0);
assert.equal(M.knowledgeSummary(crossed).rank,2);assert.equal(M.knowledgeSummary(crossed).index,2);
assert.equal(M.knowledgeSummary(crossed).complete,false);
assert.notDeepEqual(M.cognitivePosition(crossed,1,1),M.cognitivePosition(crossed,9,1));
for(const d of ['right','down','right','down','down']) assert.ok(M.move(crossed,d));
assert.equal(M.knowledgeSummary(crossed).index,1);assert.equal(M.knowledgeSummary(crossed).complete,true);
assert.deepEqual(M.cognitivePosition(crossed,1,1),M.cognitivePosition(crossed,9,1));
assert.equal(crossed.world.validation.topology.index,1);
const seen=new Set([...crossed.cognition.memory_nodes.values()].filter(n=>n.terrain).map(n=>n.world_id));
assert.ok(seen.size<=crossed.world.validation.floors);
const copy=M.knowledgeSummary(crossed);copy.vectors[0][0]=999;
assert.equal(M.knowledgeSummary(crossed).index,1,'summary cannot mutate knowledge');
const reset=M.createGame(crossed.world);assert.equal(M.knowledgeSummary(reset).index,2);
const off=M.createGame({...crossed.world,loopLearning:false});assert.equal(M.knowledgeSummary(off).rank,0);
console.log('PASS: no/one/two-direction knowledge, index-two copies, complete lattice after new observation, snapshot isolation and reset.');
