const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/app.js','utf8'),nodes=new Map();let created=0,renders=0,focused=0;
const element=()=>({textContent:'',children:[],events:{},replaceChildren(){this.children=[];},append(child){this.children.push(child);},addEventListener(name,fn){this.events[name]=fn;},focus(){focused++;}});
const $=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};
const game={cognition:{archives:Array.from({length:5},()=>({}))},turns:32,steps:31};
const context={game,$,document:{createElement(){created++;return element();}},renderArchive(){renders++;}};
vm.runInNewContext(source.slice(source.indexOf('function openMatchRecord('),source.indexOf('function renderArchive(')),context);
const reasons=['matched','ready','no-common','orientation-multiple','terrain'];
const before=JSON.stringify(game);context.renderMatchingOverview(reasons);
assert.equal($('archiveMatchList').children.length,5);assert.match($('archiveMatchSummary').textContent,/保存 5冊.*照合済み 1冊.*照合可能 1冊.*保留 3冊/);
const buttons=$('archiveMatchList').children.map(item=>item.children[0]);assert.match(buttons[3].textContent,/位置・向きの候補が複数/);
for(let i=0;i<100;i++)context.renderMatchingOverview([...reasons]);assert.equal(created,10);assert.equal($('archiveMatchList').children[3].children[0],buttons[3]);
buttons[3].events.click();assert.equal($('archiveOriginals').checked,true);assert.equal($('archiveChoice').value,'3');assert.equal(renders,2);assert.equal(focused,1);assert.equal(JSON.stringify(game),before);
for(const invalid of [-1,5,NaN,1.5])context.openMatchRecord(invalid);assert.equal(renders,2);
context.renderMatchingOverview(['matched','matched','no-common','orientation-multiple','terrain']);assert.equal(created,20);assert.match($('archiveMatchSummary').textContent,/照合済み 2冊.*照合可能 0冊/);
context.game={cognition:{archives:game.cognition.archives}};context.renderMatchingOverview(['matched','matched','no-common','orientation-multiple','terrain']);assert.equal(created,30);
context.renderMatchingOverview([]);assert.equal($('archiveMatchList').children.length,0);assert.match($('archiveMatchSummary').textContent,/保存 0冊/);
console.log('PASS: all-record counts, reason labels, button navigation without gameplay mutation, invalid indexes, stable nodes over 100 redraws, changed reasons, new game and empty lists.');

context.game=game;
const filter=$('archiveMatchFilter'),list=$('archiveMatchList'),empty=$('archiveMatchEmpty');
filter.value='pending';context.renderMatchingOverview(reasons);assert.equal(list.children.length,3);assert.match(list.children[0].children[0].textContent,/記録 3：/);assert(empty.hidden);
list.children[0].children[0].events.click();assert.equal($('archiveChoice').value,'2','filtered row uses original index');
const pendingButtons=list.children.slice(),pendingCreates=created;context.renderMatchingOverview([...reasons]);assert.equal(created,pendingCreates);assert.equal(list.children[0],pendingButtons[0]);
assert.match($('archiveMatchSummary').textContent,/保存 5冊.*保留 3冊/);
filter.value='ready';context.renderMatchingOverview(reasons);assert.equal(list.children.length,1);assert.match(list.children[0].children[0].textContent,/記録 2：/);
context.renderMatchingOverview(['matched','matched','no-common','orientation-multiple','terrain']);assert.equal(list.children.length,0);assert.equal(empty.hidden,false);assert.match(empty.textContent,/照合できる未照合の記録はありません/);
filter.value='matched';context.renderMatchingOverview(reasons);assert.equal(list.children.length,1);assert.match(list.children[0].children[0].textContent,/記録 1：/);
filter.value='pending';context.renderMatchingOverview(['matched','matched']);assert.equal(empty.hidden,false);assert.match(empty.textContent,/保留中の記録はありません/);
filter.value='all';context.renderMatchingOverview(reasons);assert.equal(list.children.length,5);assert(empty.hidden);assert.equal(JSON.stringify(game),before);
const start=source.indexOf("$('archiveMatchFilter').addEventListener");vm.runInNewContext(source.slice(start,source.indexOf(';',start)+1),context);const previousRenders=renders;filter.events.change();assert.equal(renders,previousRenders+1);
console.log('PASS: all/pending/ready/matched filters, original record navigation, stable filtered rows, full counts, empty messages, status updates, change handler and no state mutation.');
